# -*- coding: utf-8 -*-
"""Fiktivní požadavky Matice shody – Projekt SENTINEL (výměna KYC/AML řešení).

Každý požadavek: (ID, oblast, text, zdroj/zdůvodnění, vlastník, MoSCoW, K.O., akceptační kritérium,
                  očekávaná kapitola FS, stav projednání, poznámka z workshopu)
"""

OBLASTI = {
    "KYC": "Onboarding a kontrola klienta (KYC/CDD)",
    "SCR": "Screening (sankce, PEP, adverse media)",
    "TM": "Monitoring transakcí",
    "CAS": "Správa případů a rozhodování",
    "REP": "Reporting a součinnost s FAÚ",
    "INT": "Integrace",
    "MIG": "Datová migrace",
    "NFR": "Nefunkční požadavky",
    "SEC": "Bezpečnost",
    "REG": "Regulatorní soulad a auditovatelnost",
    "LEG": "Právní a smluvní požadavky",
}

# Oblasti, jejichž odpovědi se bodují do kategorie „Byznys funkcionality (30 %)"
BYZNYS = {"KYC", "SCR", "TM", "CAS", "REP"}
SMLUVNI = {"LEG"}

AML = "z. č. 253/2008 Sb."

POZADAVKY = [
    # ---------------- KYC ----------------
    ("KYC-001", "KYC", "Systém při onboardingu automaticky vypočte rizikový profil klienta (nízké / střední / vysoké / nepřijatelné riziko) z konfigurovatelných rizikových faktorů: typ klienta, země (bydliště, občanství, sídlo, zdroj majetku), produkt, distribuční kanál, objem aktiv a struktura vlastnictví.",
     f"§ 21a {AML}; vyhl. ČNB č. 67/2018 Sb.; EBA/GL/2021/02", "Compliance", "Must", "Ne",
     "Compliance bez zásahu dodavatele změní váhu faktoru v UI; změna po schválení čtyřma očima platí pro nové výpočty do 1 prac. dne.", "6.1", "Schváleno", ""),
    ("KYC-002", "KYC", "U každého výpočtu rizikového profilu je uložen vstup, použitá verze rizikového modelu, dílčí skóre faktorů a výsledné zdůvodnění; výpočet lze zpětně zrekonstruovat.",
     f"§ 21 {AML}; požadavek interního auditu", "Compliance", "Must", "Ne",
     "Pro vzorek 20 klientů lze k libovolnému datu zobrazit, proč měli daný rizikový profil.", "9.2", "Schváleno", "Nález interního auditu 2025 k současnému systému."),
    ("KYC-003", "KYC", "Systém vynutí zesílenou kontrolu (EDD) pro vysoce rizikové klienty, PEP a klienty s vazbou na vysoce rizikové třetí země dle seznamu Evropské komise; workflow obsahuje povinné kroky, schválení vedoucím a uložení podkladů.",
     f"§ 9a {AML}; nařízení v přenesené pravomoci (EU) 2016/1675", "Compliance", "Must", "Ne",
     "Onboarding PEP klienta nelze dokončit bez vyplnění všech povinných kroků EDD a schválení členem vedení dle vnitřního předpisu.", "6.1", "Schváleno", ""),
    ("KYC-004", "KYC", "Evidence a ověření skutečného majitele (UBO) včetně vícevrstvých vlastnických struktur (holdingy, svěřenské fondy, trusty, nadace) s grafickou vizualizací struktury a výpočtem nepřímého podílu.",
     f"§ 9 odst. 2 písm. b) {AML}; z. č. 37/2021 Sb.", "Compliance", "Must", "Ne",
     "Struktura se 4 úrovněmi vlastnictví a svěřenským fondem se zobrazí graficky a systém určí UBO dle prahu 25 %.", "6.1", "Schváleno", "Cca 40 % klientů PO má vícevrstvou strukturu."),
    ("KYC-005", "KYC", "Porovnání evidovaných skutečných majitelů s Evidencí skutečných majitelů (ESM) a podpora procesu hlášení nesrovnalosti.",
     "z. č. 37/2021 Sb.", "Compliance", "Should", "Ne",
     "Systém označí rozdíl mezi UBO v bance a výpisem z ESM a vytvoří úkol pro Compliance.", "5.6", "Schváleno", ""),
    ("KYC-006", "KYC", "Načtení údajů o právnické osobě z veřejných rejstříků (ARES, obchodní rejstřík) při onboardingu i při revizi.",
     "Efektivita procesu", "Obchod", "Should", "Ne",
     "Po zadání IČO se předvyplní název, sídlo, statutární orgán a datum vzniku.", "5.6", "Schváleno", ""),
    ("KYC-007", "KYC", "Příjem výsledku vzdálené identifikace klienta prostřednictvím bankovní identity (BankID) a jeho uložení jako důkazu o identifikaci.",
     "z. č. 250/2017 Sb.; EBA/GL/2022/15", "Obchod", "Could", "Ne",
     "Identifikace přes BankID se propíše do KYC záznamu včetně úrovně záruky.", "5.6", "Schváleno s úpravou", "Obchod požadoval Must; snížení na Could, privátní klienti se onboardují osobně (rozhodnutí SteerCo 23. 9. 2026)."),
    ("KYC-008", "KYC", "Periodická revize klienta plánovaná podle rizikovosti (vysoké 1 rok, střední 3 roky, nízké 5 let – konfigurovatelné) s automatickým založením úkolu pro obchodníka v CRM.",
     f"§ 9 odst. 1 {AML}; vnitřní předpis Banky", "Compliance", "Must", "Ne",
     "60 dní před termínem revize vznikne v CRM úkol přiřazený obchodníkovi klienta.", "6.1", "Schváleno", ""),
    ("KYC-009", "KYC", "Událostmi řízená revize: změna rizikově relevantního údaje v CRM (adresa, státní občanství, UBO, předmět podnikání) vyvolá přepočet rizikového profilu a re-screening do 15 minut.",
     f"§ 9 {AML}", "Compliance", "Must", "Ne",
     "Změna státního občanství na zemi z vysoce rizikového seznamu zvýší rizikovost do 15 minut a vytvoří případ.", "5.1", "Schváleno", ""),
    ("KYC-010", "KYC", "Strukturovaný dotazník ke zdroji majetku (SoW) a zdroji finančních prostředků (SoF) s možností přiložit doklady, s verzováním odpovědí a vyhodnocením věrohodnosti.",
     f"§ 9 odst. 2 písm. c) a § 9a {AML}", "Obchod", "Must", "Ne",
     "Obchodník vyplní SoW/SoF v CRM, doklady se uloží do DMS a každá změna je dohledatelná.", "6.1", "Schváleno", "Klíčové pro privátní bankovnictví."),
    ("KYC-011", "KYC", "Obchodník vidí stav KYC, rizikovost, termín revize a otevřené případy klienta přímo v CRM bez přepnutí do jiné aplikace (embedded komponenta nebo API).",
     "Případová studie: CRM je core aplikace", "Obchod", "Must", "Ne",
     "Na kartě klienta v CRM se zobrazí stav KYC do 2 s.", "5.1", "Schváleno", ""),
    ("KYC-012", "KYC", "Formuláře KYC se předvyplní z dat CRM; obchodník nezadává žádný údaj dvakrát.",
     "Efektivita procesu", "Obchod", "Should", "Ne",
     "Při revizi existujícího klienta jsou předvyplněny všechny údaje evidované v CRM.", "5.1", "Schváleno", ""),
    ("KYC-013", "KYC", "Klientské formuláře a dotazníky v češtině, angličtině a němčině; další jazyk lze doplnit konfigurací.",
     "Klientská báze Banky", "Obchod", "Should", "Ne",
     "Administrátor přidá jazykovou mutaci formuláře bez vývoje.", "6.1", "Schváleno", ""),
    ("KYC-014", "KYC", "Eskalace nesplněné revize: po termínu upozornění obchodníkovi, po 30 dnech jeho nadřízenému a Compliance, po 90 dnech návrh na omezení služeb.",
     "Vnitřní předpis Banky", "Compliance", "Should", "Ne",
     "Eskalační kroky a lhůty jsou konfigurovatelné a jejich provedení je zaznamenáno.", "6.1", "Schváleno", ""),
    ("KYC-015", "KYC", "Podpora zjednodušené kontroly klienta (SDD) pro definované kategorie klientů s nízkým rizikem.",
     f"§ 13 {AML}", "Compliance", "Could", "Ne",
     "Pro klienta kategorie SDD systém nevyžaduje kroky, které zákon u SDD nevyžaduje.", "6.1", "Schváleno", ""),
    # ---------------- SCR ----------------
    ("SCR-001", "SCR", "Screening klientů, zástupců, skutečných majitelů a protistran proti sankčním seznamům EU (konsolidovaný seznam), OSN, národnímu sankčnímu seznamu ČR a volitelně OFAC a UK HMT.",
     "z. č. 69/2006 Sb.; z. č. 1/2023 Sb.; sankční nařízení EU", "Compliance", "Must", "Ano",
     "Testovací subjekty ze všech uvedených seznamů jsou zachyceny ve skriptovaném demu.", "6.2", "Schváleno", ""),
    ("SCR-002", "SCR", "Screening politicky exponovaných osob (PEP) včetně rodinných příslušníků a osob blízkých (RCA), s rozlišením domácích a zahraničních PEP.",
     f"§ 4 odst. 5 a § 9a {AML}", "Compliance", "Must", "Ne",
     "Shoda na PEP vytvoří případ s kategorií PEP a vazbou na EDD workflow.", "6.2", "Schváleno", ""),
    ("SCR-003", "SCR", "Screening negativních zpráv (adverse media) s konfigurovatelnými kategoriemi (finanční kriminalita, korupce, organizovaný zločin, daňové delikty).",
     "EBA/GL/2021/02", "Compliance", "Should", "Ne",
     "Compliance zapne/vypne kategorie a nastaví stáří zpráv bez vývoje.", "6.2", "Schváleno", ""),
    ("SCR-004", "SCR", "Denní re-screening celé klientské báze a mimořádný re-screening do 1 hodiny od zveřejnění změny sankčního seznamu EU.",
     "čl. 5d nařízení (EU) č. 260/2012 ve znění nařízení (EU) 2024/886; z. č. 69/2006 Sb.", "Compliance", "Must", "Ne",
     "Nová designace na seznamu EU vytvoří případ u dotčeného klienta do 1 hodiny od načtení seznamu.", "6.2", "Schváleno", ""),
    ("SCR-005", "SCR", "Fuzzy matching jmen s podporou transliterace (cyrilice, arabské písmo, čínské znaky), zaměnitelných pořadí jmen a diakritiky; prahy shody nastavitelné bez vývoje.",
     "Snížení false positive", "Compliance", "Must", "Ne",
     "Jméno v cyrilici je spárováno s latinkou dle ICAO i BGN/PCGN transliterace.", "6.2", "Schváleno", ""),
    ("SCR-006", "SCR", "Seznam vyloučených shod (good-guy / whitelist) s povinným schválením čtyřma očima, zdůvodněním a datem expirace.",
     "Snížení false positive; auditovatelnost", "Compliance", "Must", "Ne",
     "Výjimka bez druhého schválení se neaplikuje; po expiraci se shoda znovu vyhodnotí.", "6.2", "Schváleno", ""),
    ("SCR-007", "SCR", "Online screening odchozích a příchozích zahraničních plateb (SWIFT, SEPA) vůči sankčním seznamům před jejich zpracováním, s možností pozastavit platbu.",
     "z. č. 69/2006 Sb.; sankční nařízení EU", "Compliance", "Must", "Ne",
     "Platba na sankcionovaný subjekt je pozastavena a vznikne případ; odezva viz NFR-003.", "5.4", "Schváleno", ""),
    ("SCR-008", "SCR", "Měření míry falešně pozitivních shod a možnost otestovat změnu nastavení screeningu nad historickými daty (what-if) před nasazením.",
     "Efektivita Compliance", "Compliance", "Should", "Ne",
     "Simulace změny prahu ukáže počet alertů za posledních 6 měsíců před a po změně.", "6.2", "Schváleno", "Dnešní FP rate cca 97 %."),
    ("SCR-009", "SCR", "Řešení podporuje alespoň dva komerční zdroje dat PEP/adverse media; náklady na datové zdroje jsou uvedeny v cenové nabídce.",
     "Riziko vendor lock-in; TCO", "IT", "Should", "Ne",
     "Výměna zdroje dat nevyžaduje změnu integrací Banky.", "3.3", "Schváleno", ""),
    ("SCR-010", "SCR", "Uchování historie screeningu (verze seznamu, výsledek, rozhodnutí, uživatel) po dobu 10 let od ukončení obchodního vztahu.",
     f"§ 16 {AML}", "Compliance", "Must", "Ne",
     "Pro libovolné datum lze doložit, proti které verzi seznamu byl klient prověřen.", "9.2", "Schváleno", ""),
    # ---------------- TM ----------------
    ("TM-001", "TM", "Monitoring transakcí pomocí konfigurovatelných scénářů; dodávaná knihovna obsahuje min. 40 typologií relevantních pro privátní bankovnictví (strukturování, rychlý průtok, rizikové země, nesoulad s profilem).",
     f"§ 21 {AML}; vyhl. ČNB č. 67/2018 Sb.", "Compliance", "Must", "Ne",
     "Dodavatel předloží seznam scénářů; 10 vybraných předvede ve skriptovaném demu.", "6.3", "Schváleno", ""),
    ("TM-002", "TM", "Compliance vytváří a mění scénáře v UI bez vývoje dodavatele; změny se verzují a schvalují čtyřma očima.",
     "Nezávislost na dodavateli", "Compliance", "Must", "Ne",
     "Nový scénář založený v UI je po schválení aktivní v produkci bez nasazení nové verze.", "6.3", "Schváleno", ""),
    ("TM-003", "TM", "Testování (backtesting) nového nebo upraveného scénáře nad historickými daty před nasazením.",
     "Kvalita detekce", "Compliance", "Should", "Ne",
     "Výsledek backtestu nad 12 měsíci dat je k dispozici do 4 hodin.", "6.3", "Schváleno", ""),
    ("TM-004", "TM", "Kontrola úplnosti informací o plátci a příjemci u bezhotovostních převodů a hlášení neúplných zpráv.",
     "nařízení (EU) 2023/1113", "Compliance", "Should", "Ne",
     "Platba bez povinných údajů plátce vytvoří alert dle konfigurace.", "6.3", "Schváleno", ""),
    ("TM-005", "TM", "Profil očekávaného chování klienta (obrat, země, typy transakcí dle KYC) a alert při významné odchylce skutečnosti od profilu.",
     f"§ 9 odst. 2 písm. d) {AML}", "Compliance", "Must", "Ne",
     "Měsíční obrat přesahující deklarovaný o nastavitelné % vytvoří alert.", "6.3", "Schváleno", ""),
    ("TM-006", "TM", "Podpora odkladu splnění příkazu klienta: pozastavení odchozí platby na základě alertu a evidence lhůt odkladu.",
     f"§ 20 {AML}", "Compliance", "Must", "Ne",
     "Pozastavená platba je evidována s časem a lhůtou; uvolnění vyžaduje rozhodnutí oprávněné osoby.", "5.4", "Schváleno", ""),
    ("TM-007", "TM", "Detekce anomálií pomocí strojového učení jako doplněk scénářů, s vysvětlením důvodu alertu srozumitelným pro analytika.",
     "nařízení (EU) 2024/1689 (AI Act) – transparentnost", "Compliance", "Could", "Ne",
     "Každý ML alert obsahuje 3 hlavní faktory, které ho způsobily.", "6.3", "Schváleno", ""),
    ("TM-008", "TM", "Při spuštění systém zpracuje transakční historii za 24 měsíců pro výpočet profilů a baseline scénářů.",
     "Kontinuita monitoringu", "Compliance", "Should", "Ne",
     "První den produkce jsou profily klientů vypočteny z migrované historie.", "7.2", "Schváleno", ""),
    # ---------------- CAS ----------------
    ("CAS-001", "CAS", "Jednotná správa případů pro alerty ze screeningu, monitoringu transakcí a KYC, s prioritizací, přidělováním a sledováním lhůt zpracování.",
     "Efektivita Compliance", "Compliance", "Must", "Ne",
     "Analytik vidí jednu frontu případů ze všech zdrojů s barevně odlišenou lhůtou.", "6.4", "Schváleno", ""),
    ("CAS-002", "CAS", "Rozhodnutí o přijetí, zamítnutí, blokaci nebo ukončení vztahu probíhá na principu čtyř očí; systém nedovolí, aby rozhodl uživatel, který případ připravil.",
     "Vnitřní kontrolní systém; vyhl. ČNB č. 67/2018 Sb.", "Compliance", "Must", "Ne",
     "Pokus o schválení vlastního případu systém odmítne a zaloguje.", "6.4", "Schváleno", ""),
    ("CAS-003", "CAS", "Rozhodnutí se do 1 minuty propíše do CRM jako stav klienta (aktivní / v prověření / blokován / ukončen) a CRM podle stavu omezí dostupné akce.",
     "Případová studie: rozhodovací procesy v CRM", "Obchod", "Must", "Ne",
     "Po blokaci nelze v CRM založit nový produkt klientovi.", "5.1", "Schváleno", ""),
    ("CAS-004", "CAS", "Zamítnutí nebo blokaci klienta vždy potvrzuje člověk; plně automatické rozhodnutí je možné jen v předem schválených případech (např. přesná shoda se sankčním seznamem).",
     "čl. 22 GDPR", "Legal", "Must", "Ne",
     "Konfigurace automatických rozhodnutí je oddělena a změnu schvaluje Compliance i DPO.", "6.4", "Schváleno s úpravou", "Obchod chtěl automatické schvalování nízkého rizika; Legal + Compliance trvají na lidském rozhodnutí u negativních výsledků."),
    ("CAS-005", "CAS", "Úplná a neměnná auditní stopa případu: kdo, kdy, jakou akci, s jakým zdůvodněním a s jakými podklady.",
     f"§ 16 {AML}; DORA čl. 12", "Compliance", "Must", "Ne",
     "Auditní záznam nelze upravit ani smazat ani administrátorem.", "9.2", "Schváleno", ""),
    ("CAS-006", "CAS", "Přílohy případu se ukládají do bankovního DMS; systém drží pouze odkaz a metadata.",
     "Architektonický princip Banky", "IT", "Should", "Ne",
     "Dokument nahraný k případu je dohledatelný v DMS s identifikátorem případu.", "5.5", "Schváleno", ""),
    ("CAS-007", "CAS", "Eskalace případu na pověřenou osobu (MLRO) a příprava podkladu pro oznámení podezřelého obchodu s předvyplněním údajů z případu.",
     f"§ 18 a § 22 {AML}", "Compliance", "Must", "Ne",
     "Z případu lze jedním krokem vytvořit koncept OPO s údaji o klientovi a transakcích.", "6.4", "Schváleno", ""),
    ("CAS-008", "CAS", "Hromadné uzavření alertů je možné jen s povinným zdůvodněním a zvláštním oprávněním.",
     "Auditovatelnost", "Compliance", "Could", "Ne",
     "Uživatel bez oprávnění funkci nevidí; hromadná akce je v auditní stopě.", "6.4", "Schváleno", ""),
    # ---------------- REP ----------------
    ("REP-001", "REP", "Generování oznámení podezřelého obchodu (OPO) ve struktuře požadované Finančním analytickým úřadem pro elektronické podání.",
     f"§ 18 {AML}; metodika FAÚ", "Compliance", "Must", "Ne",
     "Vygenerovaný soubor projde validací formátu FAÚ bez ručních úprav.", "6.5", "Schváleno", ""),
    ("REP-002", "REP", "Manažerský reporting: počty alertů a případů, backlog, doba zpracování, míra falešně pozitivních shod, rozložení rizikovosti klientské báze.",
     "Řízení Compliance; zpráva pro představenstvo", "Compliance", "Should", "Ne",
     "Report je dostupný v UI a exportovatelný do XLSX a PDF.", "6.5", "Schváleno", ""),
    ("REP-003", "REP", "Podklady pro výroční hodnocení rizik a systému vnitřních zásad a pro pravidelný sběr dat ČNB v oblasti AML.",
     f"§ 21 a § 21a {AML}; vyhl. ČNB č. 67/2018 Sb.", "Compliance", "Should", "Ne",
     "Předdefinované exporty pokrývají ukazatele, které Banka reportuje ČNB.", "6.5", "Schváleno", ""),
    ("REP-004", "REP", "Vyhledání všech údajů o klientovi, jeho případech a transakcích za zadané období pro odpověď na dotaz FAÚ nebo orgánu činného v trestním řízení.",
     f"§ 24 {AML}", "Compliance", "Must", "Ne",
     "Kompletní export pro jednoho klienta za 5 let je hotov do 1 hodiny.", "6.5", "Schváleno", ""),
    # ---------------- INT ----------------
    ("INT-001", "INT", "Obousměrná integrace s CRM přes REST API: požadavek na onboarding, stav KYC, rizikový profil, termín revize a rozhodnutí; změny z AML se do CRM posílají událostmi.",
     "Případová studie: CRM je core aplikace", "IT", "Must", "Ano",
     "Integrační scénáře onboardingu, revize a blokace projdou E2E testem v SIT.", "5.1", "Schváleno", ""),
    ("INT-002", "INT", "Systém se napojí na core banking přes bankovní Kafka sběrnici (události transakcí a změn klientských dat).",
     "Architektonický standard Banky (event-driven)", "IT", "Must", "Ne",
     "Konzumace topiců transakcí v objemu dle NFR-003 bez ztráty zpráv.", "5.2", "Schváleno", "Point-to-point integrace na core nebude akceptována."),
    ("INT-003", "INT", "Integrace na bankovní ESB (REST/SOAP) pro legacy systémy, které nemají Kafka rozhraní.",
     "Architektonický standard Banky", "IT", "Should", "Ne",
     "Ověřeno na rozhraní systému správy aktiv.", "5.3", "Schváleno", ""),
    ("INT-004", "INT", "Synchronní integrace s platebním systémem pro screening a pozastavení plateb (viz SCR-007, TM-006).",
     "Sankční povinnosti", "IT", "Must", "Ne",
     "Platební systém dostane odpověď (uvolnit / pozastavit) v limitu NFR-003.", "5.4", "Schváleno", ""),
    ("INT-005", "INT", "Denní export dat (klienti, rizikové profily, alerty, případy) do DWH v dokumentovaném datovém modelu (CSV nebo Parquet).",
     "Reporting a datová správa", "IT", "Must", "Ne",
     "Export je k dispozici do 6:00 a obsahuje popis změn modelu mezi verzemi.", "5.5", "Schváleno", ""),
    ("INT-006", "INT", "Napojení na bankovní DMS přes jeho REST API.",
     "Architektonický princip Banky", "IT", "Should", "Ne",
     "Viz CAS-006.", "5.5", "Schváleno", ""),
    ("INT-007", "INT", "Předávání bezpečnostních a auditních logů do SIEM Banky (Splunk) v reálném čase.",
     "DORA čl. 10; bezpečnostní politika Banky", "IT", "Must", "Ne",
     "Přihlášení, změna oprávnění a změna konfigurace se objeví v SIEM do 1 minuty.", "5.5", "Schváleno", ""),
    ("INT-008", "INT", "Health-check endpointy a provozní metriky pro monitoring Banky (Zabbix / AppDynamics).",
     "Provozní standard Banky", "IT", "Must", "Ne",
     "Monitoring Banky zachytí nedostupnost komponenty do 2 minut.", "5.5", "Schváleno", ""),
    ("INT-009", "INT", "API je dokumentováno ve formátu OpenAPI 3, verzováno a zpětně kompatibilní min. 12 měsíců po vydání nové verze.",
     "Udržitelnost integrací", "IT", "Should", "Ne",
     "Dodavatel předloží OpenAPI specifikaci jako součást nabídky.", "5.1", "Schváleno", ""),
    ("INT-010", "INT", "Napojení na veřejné registry (ARES, ESM) přes bankovní integrační vrstvu.",
     "Viz KYC-005, KYC-006", "IT", "Could", "Ne",
     "Volání registrů jde přes ESB, ne napřímo z aplikace.", "5.6", "Schváleno", ""),
    # ---------------- MIG ----------------
    ("MIG-001", "MIG", "Migrace KYC dat, rizikových profilů, historie screeningu, alertů a případů ze současného AML systému za období 10 let.",
     f"§ 16 {AML}", "Compliance", "Must", "Ne",
     "Po migraci je u vzorku 200 klientů dohledatelná celá historie.", "7.2", "Schváleno", ""),
    ("MIG-002", "MIG", "Přechod bez přerušení onboardingu a screeningu: souběžný provoz obou systémů min. 4 týdny s porovnáním výsledků.",
     "Kontinuita služeb; DORA čl. 11", "IT", "Must", "Ne",
     "Odchylky výsledků screeningu mezi systémy jsou vysvětleny před vypnutím starého systému.", "7.3", "Schváleno", ""),
    ("MIG-003", "MIG", "Dodavatel zajistí datové mapování, profilaci a reporting kvality dat; opravu dat provádí Banka s nástroji dodavatele.",
     "Rozdělení odpovědnosti", "IT", "Should", "Ne",
     "Report kvality dat je k dispozici po každém zkušebním běhu migrace.", "7.2", "Schváleno", ""),
    ("MIG-004", "MIG", "Rekonciliace 100 % migrovaných záznamů kontrolními součty a počty, s protokolem podepsaným Bankou i dodavatelem.",
     "Auditovatelnost migrace", "Compliance", "Must", "Ne",
     "Protokol rekonciliace je podmínkou go-live.", "7.2", "Schváleno", ""),
    ("MIG-005", "MIG", "Plán návratu (rollback) pro každou fázi přechodu.",
     "Řízení rizik", "IT", "Must", "Ne",
     "Rollback je vyzkoušen na PreProd prostředí.", "7.3", "Schváleno", ""),
    # ---------------- NFR ----------------
    ("NFR-001", "NFR", "Dostupnost produkce 99,9 % měsíčně, měřená end-to-end syntetickými transakcemi z monitoringu Banky (viz Příloha 4 – SLA).",
     "Kritická funkce Banky", "IT", "Must", "Ne",
     "Dodavatel akceptuje metodiku měření dle Přílohy 4.", "8.1", "Schváleno", ""),
    ("NFR-002", "NFR", "RTO ≤ 4 hodiny a RPO ≤ 15 minut pro produkční prostředí; test obnovy min. 1× ročně.",
     "DORA čl. 11 a 12", "IT", "Must", "Ne",
     "Výsledek testu obnovy je doložen protokolem.", "3.4", "Schváleno", ""),
    ("NFR-003", "NFR", "Výkon: online screening subjektu ≤ 2 s (P95), screening platby ≤ 500 ms (P95), noční re-screening 60 000 subjektů ≤ 1 hodina, zpracování 1,5 mil. transakcí ročně.",
     "Objemy Banky (viz RFP kap. 4)", "IT", "Must", "Ne",
     "Výkonnostní test na PreProd prostředí s objemem +20 %.", "3.4", "Schváleno", ""),
    ("NFR-004", "NFR", "Škálovatelnost na dvojnásobek objemů bez změny architektury.",
     "Růstová strategie Banky", "IT", "Should", "Ne",
     "Dodavatel popíše způsob škálování a jeho cenový dopad.", "3.4", "Schváleno", ""),
    ("NFR-005", "NFR", "Prostředí DEV, SIT, UAT, PreProd (výkonnostní), PROD a DR.",
     "Standard Banky pro řízení změn", "IT", "Must", "Ne",
     "Všechna prostředí jsou oceněna v cenové šabloně.", "3.2", "Schváleno", ""),
    ("NFR-006", "NFR", "Provoz on-premise v datových centrech Banky nebo v privátním cloudu; data a zálohy výhradně v EU/EHP.",
     "Bezpečnostní politika Banky; GDPR; DORA", "IT", "Must", "Ano",
     "Dodavatel uvede lokality zpracování všech dat včetně záloh a podpory.", "3.1", "Schváleno", ""),
    ("NFR-007", "NFR", "Vysoká dostupnost mezi dvěma datovými centry Banky (active-passive).",
     "DORA čl. 12", "IT", "Must", "Ne",
     "Přepnutí na záložní DC proběhne do 4 hodin.", "3.4", "Schváleno", ""),
    ("NFR-008", "NFR", "Uživatelské rozhraní v češtině a angličtině.",
     "Uživatelé Banky", "Obchod", "Should", "Ne",
     "Uživatel si volí jazyk v profilu.", "6.1", "Schváleno", ""),
    ("NFR-009", "NFR", "Podpora 150 pojmenovaných a 60 souběžných uživatelů (obchod, zákaznická podpora, Compliance).",
     "Uživatelé Banky", "IT", "Must", "Ne",
     "Výkonnostní test s 60 souběžnými uživateli.", "3.4", "Schváleno", ""),
    # ---------------- SEC ----------------
    ("SEC-001", "SEC", "Systém podporuje SAML 2.0 / OIDC pro jednotné přihlášení (SSO) přes bankovní IAM.",
     "Bezpečnostní politika Banky", "IT", "Must", "Ano",
     "Přihlášení přes IAM Banky ověřeno v SIT.", "4.2", "Schváleno", ""),
    ("SEC-002", "SEC", "Řízení přístupu na základě rolí (RBAC) s granularitou na funkci a datový rozsah (segment, pobočka); report pro pravidelnou recertifikaci oprávnění.",
     "DORA čl. 9; GDPR čl. 32", "IT", "Must", "Ne",
     "Obchodník vidí pouze své klienty; report oprávnění lze exportovat.", "4.1", "Schváleno", ""),
    ("SEC-003", "SEC", "Šifrování dat v klidu (AES-256) a při přenosu (TLS 1.2 a vyšší); šifrovací klíče spravuje Banka (HSM/KMS).",
     "DORA čl. 9; GDPR čl. 32", "IT", "Must", "Ne",
     "Dodavatel doloží konfiguraci šifrování a správy klíčů.", "4.3", "Schváleno", ""),
    ("SEC-004", "SEC", "Auditní a bezpečnostní logy jsou neměnné (append-only) a uchovávané po dobu určenou Bankou.",
     "DORA čl. 12; § 16 z. č. 253/2008 Sb.", "IT", "Must", "Ne",
     "Pokus o změnu logu je detekován a hlášen do SIEM.", "4.4", "Schváleno", ""),
    ("SEC-005", "SEC", "Vícefaktorové ověření a správa privilegovaných účtů přes PAM řešení Banky.",
     "Bezpečnostní politika Banky", "IT", "Must", "Ne",
     "Administrátorský přístup je možný jen přes PAM.", "4.2", "Schváleno", ""),
    ("SEC-006", "SEC", "Dodavatel umožní penetrační testy Banky min. 1× ročně a účast v penetračních testech řízených hrozbami (TLPT).",
     "DORA čl. 24–26", "IT", "Must", "Ne",
     "Smluvně zakotveno; harmonogram testů v FS.", "4.5", "Schváleno", ""),
    ("SEC-007", "SEC", "Oprava zranitelností v dodaném software: kritické (CVSS ≥ 9,0) do 5 pracovních dnů, vysoké (7,0–8,9) do 30 dnů, bez dalších poplatků.",
     "DORA čl. 9; bezpečnostní politika Banky", "IT", "Must", "Ne",
     "Lhůty jsou součástí SLA (Příloha 4).", "4.5", "Schváleno", ""),
    ("SEC-008", "SEC", "Ke každému releasu dodavatel poskytne SBOM (seznam softwarových komponent).",
     "Řízení rizik dodavatelského řetězce", "IT", "Should", "Ne",
     "SBOM ve formátu CycloneDX nebo SPDX.", "4.5", "Schváleno", ""),
    ("SEC-009", "SEC", "Maskování nebo pseudonymizace osobních údajů v neprodukčních prostředích.",
     "čl. 25 a 32 GDPR", "Legal", "Must", "Ne",
     "Na UAT nejsou čitelná skutečná jména klientů.", "4.3", "Schváleno", ""),
    ("SEC-010", "SEC", "Dodavatel je držitelem platné certifikace ISO/IEC 27001 nebo zprávy SOC 2 Type II pro organizaci zajišťující vývoj a podporu.",
     "Řízení rizik dodavatele", "IT", "Must", "Ano",
     "Kopie certifikátu / zprávy ne starší 12 měsíců.", "4.1", "Schváleno", ""),
    # ---------------- REG ----------------
    ("REG-001", "REG", "Dodavatel akceptuje smluvní ujednání dle čl. 30 DORA a poskytne údaje pro registr informací Banky.",
     "nařízení (EU) 2022/2554 (DORA) čl. 28 a 30", "Legal", "Must", "Ano",
     "Bez výhrad k Příloze 5 v části DORA.", "9.1", "Schváleno", ""),
    ("REG-002", "REG", "Legislativní údržba je součástí ceny licence/podpory: změny AML zákona, vyhlášek ČNB a požadavky nařízení (EU) 2024/1624 (AMLR) včetně technických norem AMLA.",
     "nařízení (EU) 2024/1624 – použitelné od 10. 7. 2027", "Compliance", "Must", "Ne",
     "Dodavatel potvrdí v cenové šabloně (list C), že legislativní údržba není účtována zvlášť.", "9.1", "Schváleno", ""),
    ("REG-003", "REG", "Retenční pravidla: uchování 10 let dle AML zákona a následný výmaz nebo anonymizace dle GDPR, s protokolem.",
     f"§ 16 {AML}; čl. 5 a 17 GDPR", "Legal", "Must", "Ne",
     "Výmaz po uplynutí lhůty proběhne automaticky a je zaprotokolován.", "9.2", "Schváleno", ""),
    ("REG-004", "REG", "Dodavatel poskytne podklady pro posouzení vlivu na ochranu osobních údajů (DPIA).",
     "čl. 35 GDPR", "Legal", "Must", "Ne",
     "Podklady dodány do 30 dnů od podpisu smlouvy.", "9.1", "Schváleno", ""),
    ("REG-005", "REG", "Roadmapa produktu pro požadavky AMLR a AMLA (např. jednotná pravidla CDD, údaje o skutečných majitelích, uchovávání údajů).",
     "nařízení (EU) 2024/1624 a 2024/1620", "Compliance", "Should", "Ne",
     "Roadmapa s termíny je součástí FS.", "9.1", "Schváleno", ""),
    ("REG-006", "REG", "Dokumentace modelů strojového učení (účel, data, metriky, řízení změn) pro potřeby validace a dozoru.",
     "nařízení (EU) 2024/1689 (AI Act); řízení modelového rizika", "Compliance", "Could", "Ne",
     "Dokumentace je dostupná ke každé verzi modelu.", "9.1", "Schváleno", ""),
    # ---------------- LEG ----------------
    ("LEG-001", "LEG", "Osobní údaje jsou zpracovávány výhradně v EU/EHP; jakýkoli přístup z třetích zemí (včetně vzdálené podpory) jen s předchozím písemným souhlasem Banky.",
     "kap. V GDPR; z. č. 110/2019 Sb.", "Legal", "Must", "Ano",
     "Dodavatel uvede všechna místa zpracování a podpory.", "9.1", "Schváleno", ""),
    ("LEG-002", "LEG", "Uzavření smlouvy o zpracování osobních údajů dle čl. 28 GDPR na vzoru Banky.",
     "čl. 28 GDPR", "Legal", "Must", "Ano",
     "Bez výhrad nebo s výhradami vyřešenými v jednání.", "9.1", "Schváleno", ""),
    ("LEG-003", "LEG", "Mlčenlivost o skutečnostech podléhajících bankovnímu tajemství pro pracovníky dodavatele i subdodavatelů.",
     "§ 38 z. č. 21/1992 Sb., o bankách", "Legal", "Must", "Ne",
     "Individuální závazky mlčenlivosti před udělením přístupu.", "9.1", "Schváleno", ""),
    ("LEG-004", "LEG", "Neomezené právo auditu, přístupu a inspekce pro Banku, ČNB a další orgány dohledu, včetně subdodavatelů.",
     "DORA čl. 30 odst. 3 písm. e); EBA/GL/2019/02", "Legal", "Must", "Ne",
     "Smluvně zakotveno bez omezení četnosti pro orgány dohledu.", "9.1", "Schváleno", ""),
    ("LEG-005", "LEG", "Seznam subdodavatelů v nabídce; změna subdodavatele podílejícího se na kritické funkci jen s předchozím souhlasem Banky.",
     "DORA čl. 29 a 30; nařízení v přenesené pravomoci (EU) 2025/532", "Legal", "Must", "Ne",
     "Seznam subdodavatelů s lokalitou a rozsahem činnosti.", "9.1", "Schváleno", ""),
    ("LEG-006", "LEG", "Exitová součinnost min. 12 měsíců, export všech dat v otevřeném strojově čitelném formátu a přechodné období provozu; ocenění v cenové šabloně.",
     "DORA čl. 28 odst. 8; EBA/GL/2019/02", "Legal", "Must", "Ne",
     "Exitový plán je součástí FS (kap. 10).", "10", "Schváleno", ""),
    ("LEG-007", "LEG", "Úschova zdrojového kódu (escrow) nebo jiná záruka kontinuity při insolvenci či ukončení produktu.",
     "Řízení rizik dodavatele", "Legal", "Should", "Ne",
     "Návrh escrow ujednání.", "10", "Schváleno", ""),
    ("LEG-008", "LEG", "Limit odpovědnosti za škodu min. ve výši 200 % ročních plateb; bez limitu u porušení mlčenlivosti, ochrany osobních údajů a úmyslu.",
     "Standard smluv Banky", "Legal", "Should", "Ne",
     "Výhrady budou předmětem jednání.", "9.1", "Schváleno s úpravou", "Legal chtěl neomezenou odpovědnost; SteerCo schválil 200 % s tím, že výše je předmětem jednání v BAFO."),
    ("LEG-009", "LEG", "Smlouva se řídí českým právem; spory řeší obecné soudy ČR.",
     "Standard smluv Banky", "Legal", "Must", "Ne",
     "Bez výhrad.", "9.1", "Schváleno", ""),
    ("LEG-010", "LEG", "Pojištění odpovědnosti dodavatele s limitem plnění min. 50 mil. Kč po celou dobu trvání smlouvy.",
     "Standard smluv Banky", "Legal", "Should", "Ne",
     "Pojistný certifikát v nabídce.", "12", "Schváleno", ""),
]

# Ukázkové řádky ze zadání pro prázdnou šablonu
UKAZKY = [
    ("SEC-001", "SEC", "Systém podporuje SAML 2.0 / OIDC pro SSO.", "Bezpečnostní politika", "IT", "Must", "Ano",
     "Přihlášení přes IAM ověřeno v SIT.", "4.2", "Návrh", "Příklad – přepište"),
    ("INT-002", "INT", "Systém se umí napojit na core banking přes Kafka.", "Architektonický standard", "IT", "Must", "Ne",
     "Konzumace topiců bez ztráty zpráv.", "5.2", "Návrh", "Příklad – přepište"),
    ("FUN-045", "REP", "Generování PDF reportu s vodoznakem.", "Požadavek Compliance", "Compliance", "Should", "Ne",
     "Report obsahuje vodoznak s uživatelem a časem.", "6.5", "Návrh", "Příklad – přepište"),
]

WORKSHOPY = [
    ("WS-01", "2026-09-08", "Compliance", "MLRO, 3× AML analytik, Business analytik", "KYC, screening, správa případů", "Odsouhlaseno 34 požadavků; FP rate jako hlavní bolest.", "KYC-001–015, SCR-*, CAS-*"),
    ("WS-02", "2026-09-10", "Obchod", "Vedoucí privátního bankovnictví, 2× privátní bankéř, vedoucí zákaznické podpory, Business analytik", "Práce v CRM, onboarding, revize", "Požadavek na zobrazení KYC v CRM a předvyplnění formulářů.", "KYC-006–013, CAS-003"),
    ("WS-03", "2026-09-14", "IT", "Enterprise architekt, CRM product owner, integrační specialista, bezpečnostní architekt, Business analytik", "Architektura, integrace, NFR, bezpečnost", "Kafka jako povinný standard; zákaz point-to-point na core.", "INT-*, NFR-*, SEC-*"),
    ("WS-04", "2026-09-16", "Legal", "Právník pro IT smlouvy, DPO, Business analytik", "GDPR, DORA, bankovní tajemství, smluvní požadavky", "Data jen v EU/EHP jako K.O.; vzor DPA Banky.", "LEG-*, REG-001, REG-003–004"),
    ("WS-05", "2026-09-21", "Všichni", "Zástupci IT, Compliance, Legal, Obchodu; procurement", "Konsolidace, MoSCoW, K.O. kritéria", "Vyřešeny 3 konflikty (viz list Konflikty); seznam K.O. finalizován.", "Celá matice"),
    ("WS-06", "2026-09-23", "SteerCo", "Sponzor (člen představenstva), CIO, ředitel Compliance, ředitel PB", "Schválení matice a váhového modelu", "Matice v. 1.0 schválena; váhy 40/30/20/10 schváleny před vyhlášením.", "Celá matice"),
]

KONFLIKTY = [
    ("K-01", "CAS-004", "Obchod: automatické schválení klientů s nízkým rizikem bez zásahu Compliance.",
     "Legal/Compliance: negativní rozhodnutí vždy člověk (čl. 22 GDPR), pozitivní automaticky jen u nízkého rizika.",
     "Kompromis: automatické schválení jen u nízkého rizika bez shody ve screeningu; zamítnutí a blokace vždy člověk.", "WS-05"),
    ("K-02", "KYC-007", "Obchod: BankID jako Must pro získávání mladší generace klientů.",
     "Compliance/IT: privátní klienti se onboardují osobně, BankID zvyšuje rozsah integrací.",
     "Priorita Could; dodavatel jej ocení volitelně.", "WS-06"),
    ("K-03", "NFR-006", "IT (část): SaaS řešení v cloudu dodavatele kvůli nižším nákladům.",
     "Bezpečnost/Legal: kritická funkce, bankovní tajemství, DORA koncentrační riziko.",
     "Povolen on-premise nebo privátní cloud s daty v EU/EHP; veřejný multi-tenant SaaS mimo zadání.", "WS-05"),
]
